language: python
cache: pip

matrix:
  include:
   - env: TOXENV=py38-dj22-wagtail211
     python: 3.8
   - env: TOXENV=py39-dj22-wagtail212
     python: 3.9
   - env: TOXENV=py39-dj31-wagtail212
     python: 3.9
   - env: TOXENV=flake8
     python: 3.9
   - env: TOXENV=black
     python: 3.9
   - env: TOXENV=isort
     python: 3.9
   - env: TOXENV=py39-dj31-wagtailmain
     python: 3.9
   - env: TOXENV=py39-djmain-wagtailmain
     python: 3.9
  allow_failures:
    - env: TOXENV=py39-dj31-wagtailmain
    - env: TOXENV=py39-djmain-wagtailmain

# Run the tests
script:
  tox

install:
  - pip install tox
