language: python
cache: pip

matrix:
  include:
   - env: TOXENV=py38-dj22-wagtail29
     python: 3.8
   - env: TOXENV=py38-dj30-wagtail29
     python: 3.8
   - env: TOXENV=flake8
     python: 3.7
   - env: TOXENV=black
     python: 3.7
   - env: TOXENV=isort
     python: 3.7
   - env: TOXENV=py37-djmaster-wagtailmaster
     python: 3.7
   - env: TOXENV=py38-djmaster-wagtailmaster
     python: 3.8
  allow_failures:
    - env: TOXENV=py37-djmaster-wagtailmaster
    - env: TOXENV=py38-djmaster-wagtailmaster

# Run the tests
script:
  tox

install:
  - pip install tox
